import {
  LayoutDashboard,
  FolderOpen,
  FolderTree,
  Wrench,
  Star,
  Clock3,
  Mail,
  Shield,
  Globe,
  Server,
  Settings,
  Search,
  FileText,
  KeyRound,
  Link,
  Database,
  Cloud,
  Users,
  Rabbit,
  ShieldAlert,
  Binary,
  FileSearch,
  Network,
  Wifi,
  QrCode,
  FileCode,
  FileDiff,
} from "lucide-react";

export const ICONS = {
  dashboard: LayoutDashboard,

  category: FolderOpen,
  categories: FolderTree,

  tool: Wrench,
  script: FileCode,

  keyRound: KeyRound,

  favorite: Star,
  recent: Clock3,
  quick: Rabbit,

  users: Users,
  settings: Settings,

  mail: Mail,
  security: Shield,
  shield: Shield,
  shieldAlert: ShieldAlert,
  binary: Binary,
  dns: Globe,
  server: Server,
  cloud: Cloud,
  database: Database,
  search: Search,
  link: Link,
  file: FileText,
  fileSearch: FileSearch,
  network: Network,
  wifi: Wifi,
  qrCode: QrCode,
  fileDiff: FileDiff,
};

export const DEFAULT_ICON = Wrench;

export const ICON_LABELS = {
  dashboard: "Dashboard",
  category: "Category",
  categories: "Categories",
  tool: "Tool",
  script: "Script",
  keyRound: "Password",
  favorite: "Favorite",
  recent: "Recent",
  quick: "Quick",
  users: "Users",
  settings: "Settings",
  mail: "Mail",
  security: "Security",
  shield: "Shield",
  shieldAlert: "Shield Alert",
  binary: "Binary",
  dns: "DNS",
  server: "Server",
  cloud: "Cloud",
  database: "Database",
  search: "Search",
  link: "Link",
  file: "File",
  fileSearch: "File Search",
  network: "Network",
  wifi: "Wifi",
  qrCode: "QR Code",
  fileDiff: "File Diff",
};
